// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace ReqnRoll_Playwright_BDD_MSTEST_Framework.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class RegistrationFunctionalityForCoreOpsWebApplicationFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private Microsoft.VisualStudio.TestTools.UnitTesting.TestContext _testContext;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features", "Registration Functionality for CoreOps Web Application", "As a prospective Lubanzi Employee,\r\nI want to create a new account in the CoreOps" +
                " Employee Management system,\r\nSo that I can access the platform and perform my o" +
                "perational functions.", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
#line 1 "Register.feature"
#line hidden
        
        public virtual Microsoft.VisualStudio.TestTools.UnitTesting.TestContext TestContext
        {
            get
            {
                return this._testContext;
            }
            set
            {
                this._testContext = value;
            }
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute(Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupBehavior.EndOfClass)]
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Microsoft.VisualStudio.TestTools.UnitTesting.TestContext>(_testContext);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async global::System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
#line 6
#line hidden
#line 7
 await testRunner.GivenAsync("I am on the login page of the test system,", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 8
 await testRunner.WhenAsync("I click on the Register link,", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/Register.feature.ndjson", 12);
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("Register successfully as a new user")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Register successfully as a new user")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Registration Functionality for CoreOps Web Application")]
        public async global::System.Threading.Tasks.Task RegisterSuccessfullyAsANewUser()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Register successfully as a new user", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 10
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
await this.FeatureBackgroundAsync();
#line hidden
#line 11
await testRunner.GivenAsync("I am on the registration page of the test system,", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 12
await testRunner.WhenAsync("I enter a valid email address,", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 13
await testRunner.AndAsync("I enter my first name,", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 14
await testRunner.AndAsync("I enter my last name,", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 15
await testRunner.AndAsync("I enter my phone number,", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 16
await testRunner.AndAsync("I enter my gender,", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 17
await testRunner.AndAsync("I enter a valid password,", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 18
await testRunner.AndAsync("I click the register button,", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 19
await testRunner.ThenAsync("I will be redirected to the otp page seeing the Verify OTP button", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 20
await testRunner.AndAsync("I should recieve an email with a unique otp code.", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 21
await testRunner.WhenAsync("on the otp page, i enter my otp code in the OTP code field", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 22
await testRunner.AndAsync("click the verify OTP button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 23
await testRunner.ThenAsync("i should see a popup message with the message \"Your account has been created succ" +
                        "essfully. You can now login with your credentials.\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 24
await testRunner.AndAsync("when I click the \"OK\" button on the popup message", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 25
await testRunner.AndAsync("I should be redirected to the login page of the test system,", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 26
await testRunner.AndAsync("be able to login with the credentials I used during registration ,seeing the dash" +
                        "board message of \"Welcome To Our Dashboard\" after i login successfully.", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("Unsuccessful registration attempt with an already registered email address")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Unsuccessful registration attempt with an already registered email address")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Registration Functionality for CoreOps Web Application")]
        public async global::System.Threading.Tasks.Task UnsuccessfulRegistrationAttemptWithAnAlreadyRegisteredEmailAddress()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "1";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Unsuccessful registration attempt with an already registered email address", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 28
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
await this.FeatureBackgroundAsync();
#line hidden
#line 29
await testRunner.GivenAsync("I am on the registration page of the test system", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 30
await testRunner.WhenAsync("I enter a pre-existant email address,", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 31
await testRunner.AndAsync("I enter my first name,", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 32
await testRunner.AndAsync("I enter my last name,", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 33
await testRunner.AndAsync("I enter my phone number,", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 34
await testRunner.AndAsync("I enter my gender,", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 35
await testRunner.AndAsync("I enter a valid password,", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 36
await testRunner.AndAsync("I click the register button,", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 37
await testRunner.ThenAsync("I should remain on the registration page indicated by the url containing \"/Regist" +
                        "er\",", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 38
await testRunner.AndAsync("an error message should be displayed on the page with the message \"Email is alrea" +
                        "dy registered. Please use a different email.\".", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("Unsuccessful Registration Attempts with Invalid Data")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Unsuccessful Registration Attempts with Invalid Data")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Registration Functionality for CoreOps Web Application")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("invalid-email", "Bruce", "Wayne", "07300841554", "Male", "wE7?wG8Qh", "Invalid email format", "2", null, DisplayName="Unsuccessful Registration Attempts with Invalid Data(invalid-email,Bruce,Wayne,07" +
            "300841554,Male,wE7?wG8Qh,Invalid email format,2)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("bruce.wayne@mailsac.com", "", "Wayne", "07300841554", "Male", "wE7?wG8Qh", "First name is required", "3", null, DisplayName="Unsuccessful Registration Attempts with Invalid Data(bruce.wayne@mailsac.com,,Way" +
            "ne,07300841554,Male,wE7?wG8Qh,First name is required,3)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("bruce.wayne@mailsac.com", "Bruce", "", "07300841554", "Male", "wE7?wG8Qh", "Last name is required", "4", null, DisplayName="Unsuccessful Registration Attempts with Invalid Data(bruce.wayne@mailsac.com,Bruc" +
            "e,,07300841554,Male,wE7?wG8Qh,Last name is required,4)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("bruce.wayne@mailsac.com", "Bruce", "Wayne", "", "Male", "wE7?wG8Qh", "Phone number is required", "5", null, DisplayName="Unsuccessful Registration Attempts with Invalid Data(bruce.wayne@mailsac.com,Bruc" +
            "e,Wayne,,Male,wE7?wG8Qh,Phone number is required,5)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("bruce.wayne@mailsac.com", "Bruce", "Wayne", "07300841554", "", "wE7?wG8Qh", "Gender selection is required", "6", null, DisplayName="Unsuccessful Registration Attempts with Invalid Data(bruce.wayne@mailsac.com,Bruc" +
            "e,Wayne,07300841554,,wE7?wG8Qh,Gender selection is required,6)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("bruce.wayne@mailsac.com", "Bruce", "Wayne", "07300841554", "Male", "", "Password is required", "7", null, DisplayName="Unsuccessful Registration Attempts with Invalid Data(bruce.wayne@mailsac.com,Bruc" +
            "e,Wayne,07300841554,Male,,Password is required,7)")]
        public async global::System.Threading.Tasks.Task UnsuccessfulRegistrationAttemptsWithInvalidData(string email, string firstName, string lastName, string phoneNumber, string gender, string password, string expected_Message, string @__pickleIndex, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("email", email);
            argumentsOfScenario.Add("firstName", firstName);
            argumentsOfScenario.Add("lastName", lastName);
            argumentsOfScenario.Add("phoneNumber", phoneNumber);
            argumentsOfScenario.Add("gender", gender);
            argumentsOfScenario.Add("password", password);
            argumentsOfScenario.Add("Expected_message", expected_Message);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Unsuccessful Registration Attempts with Invalid Data", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 40
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
await this.FeatureBackgroundAsync();
#line hidden
#line 41
 await testRunner.GivenAsync("I am on the registration page of the test system,", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 42
 await testRunner.WhenAsync(string.Format("I enter an email address \"{0}\",", email), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 43
 await testRunner.AndAsync(string.Format("I enter a first name \"{0}\",", firstName), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 44
 await testRunner.AndAsync(string.Format("I enter a last name \"{0}\",", lastName), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 45
 await testRunner.AndAsync(string.Format("I enter a phone number \"{0}\",", phoneNumber), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 46
 await testRunner.AndAsync(string.Format("I select a gender \"{0}\",", gender), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 47
 await testRunner.AndAsync(string.Format("I enter a password \"{0}\",", password), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 48
 await testRunner.AndAsync("I click the register button,", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 49
 await testRunner.ThenAsync("I should remain on the registration page indicated by the url containing \"/Regist" +
                        "er\",", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 50
 await testRunner.AndAsync(string.Format("I should see an error message \"{0}\" detailing the reason for the failed registrat" +
                            "ion.", expected_Message), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("Verify Password Strength Indicator")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Verify Password Strength Indicator")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Registration Functionality for CoreOps Web Application")]
        public async global::System.Threading.Tasks.Task VerifyPasswordStrengthIndicator()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "8";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Verify Password Strength Indicator", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 61
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
await this.FeatureBackgroundAsync();
#line hidden
#line 62
 await testRunner.GivenAsync("I am on the registration page of the test system,", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 63
 await testRunner.WhenAsync("I enter a weak password \"123\",", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 64
 await testRunner.ThenAsync("I should see a password strength message of \"Weak\" on the page,", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 65
 await testRunner.WhenAsync("I enter a strong password \"Abc@123456789!\",", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 66
 await testRunner.ThenAsync("I should see a password strength message of \"Strong\" on the page.", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("Navigate back to Login Page from Registration Page")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Navigate back to Login Page from Registration Page")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Registration Functionality for CoreOps Web Application")]
        public async global::System.Threading.Tasks.Task NavigateBackToLoginPageFromRegistrationPage()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "9";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Navigate back to Login Page from Registration Page", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 68
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
await this.FeatureBackgroundAsync();
#line hidden
#line 69
 await testRunner.GivenAsync("I am on the registration page of the test system,", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 70
 await testRunner.WhenAsync("I click the login link on the registration page,", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 71
 await testRunner.ThenAsync("I should be redirected to the login page indicated by the url containing \"/Login\"" +
                        ",", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 72
 await testRunner.AndAsync("I should see the login page header \"Login to your account\".", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
